route:
  group_by: ['alertname']
  receiver: 'telegram'
  repeat_interval: 1h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: 'xxxxxxxxxxxxxxxxxxxx'
        chat_id: -000000000
        parse_mode: "MarkdownV2"
        message: '{{ template "telegram.alert_list" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'
