{
 "title": "Blackbox Exporter",
 "description": "Blackbox Exporter Node",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$target Network Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "target" },
  {
   "title": "Current Status Response ",
   "type": "stat",
   "description": "Response HTTP status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{ instane }}" }
   ]
  },
  {
   "title": "DNS Response (Latency)",
   "type": "timeseries",
   "description": "Time taken for website DNS lookup in milli-seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Ping Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "description": "Specifies whether probe ip protocol is IP4 or IP6",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ip_protocol{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  }
 ]
}